name=littleloop
version=0.0.1
author=Viktor "zamonary1" Ershov <zamonary1@duck.com>
maintainer=Viktor "zamonary1" Ershov <zamonary1@duck.com>
sentence=Minimal RTOS-like task runner
paragraph=Has a tiny footprint, no external dependencies and very easy integration for existing projects or new hardware.
category=Other
url=https://github.com/zamonary1/littleloop
architectures=*
